/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerPedido;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Pedido;

/**
 *
 * @author Luan Riechi
 */
public class JanelaPedidos extends javax.swing.JFrame {
    ControllerPedido controle = new ControllerPedido();

    public void LoadTable (){
        DefaultTableModel modelo = new DefaultTableModel (new Object[]{"ID","Lanche","Adicional","Preco"},0);
        
        for (int i=0 ; i<controle.lista.size();i++){
            Object linha[] = new Object []{controle.lista.get(i).getId(),controle.lista.get(i).getLanche(),controle.lista.get(i).getAdicional(),controle.lista.get(i).getPreco()};
            modelo.addRow(linha);
        
        }
      
        tblPedido.setModel(modelo);
    
    }
    public void LoadTable1 (){
        DefaultTableModel modelo = new DefaultTableModel (new Object[]{"ID","Lanche","Adicional","Preco"},0);
        
        for (int i=0 ; i<controle.lista.size();i++){
            Object linha[] = new Object []{controle.lista.get(i).getId(),controle.lista.get(i).getLanche(),controle.lista.get(i).getAdicional(),controle.lista.get(i).getPreco()};
            modelo.addRow(linha);
        
        }
      
        tblPedido1.setModel(modelo);
    
    }
    public void LoadTable2 (){
        DefaultTableModel modelo = new DefaultTableModel (new Object[]{"ID","Lanche","Adicional","Preco"},0);
        
        for (int i=0 ; i<controle.lista.size();i++){
            Object linha[] = new Object []{controle.lista.get(i).getId(),controle.lista.get(i).getLanche(),controle.lista.get(i).getAdicional(),controle.lista.get(i).getPreco()};
            modelo.addRow(linha);
        
        }
      
        tblPedido2.setModel(modelo);
    
    }    

    /**
     * Creates new form JanelaPedidos
     */
    public JanelaPedidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedido = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txId = new javax.swing.JTextField();
        txLanche = new javax.swing.JTextField();
        txPreco = new javax.swing.JTextField();
        txAdicional = new javax.swing.JTextField();
        bntCadastrar = new javax.swing.JButton();
        bntEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPedido1 = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPedido2 = new javax.swing.JTable();
        jTextField6 = new javax.swing.JTextField();
        btnLer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Lanche", "Adicional", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPedido);

        jLabel1.setText("ID");

        jLabel2.setText("Lanche");

        jLabel3.setText("Preço em R$");

        jLabel4.setText("Adicional");

        txId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIdActionPerformed(evt);
            }
        });

        txAdicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txAdicionalActionPerformed(evt);
            }
        });

        bntCadastrar.setText("Cadastrar");
        bntCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCadastrarActionPerformed(evt);
            }
        });

        bntEditar.setText("Editar");
        bntEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar(ID)");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txId)
                    .addComponent(txLanche)
                    .addComponent(txPreco)
                    .addComponent(txAdicional, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bntCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpar)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txLanche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntCadastrar)
                    .addComponent(bntEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnPesquisar)
                    .addComponent(btnLimpar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pedidos", jPanel1);

        tblPedido1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Lanche", "Adicional", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPedido1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedido1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPedido1);

        btnSalvar.setText("Salvar arquivo");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar))
                .addGap(65, 65, 65))
        );

        jTabbedPane1.addTab("Salvar arquivo", jPanel2);

        tblPedido2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Lanche", "Adicional", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPedido2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedido2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPedido2);

        btnLer.setText("Ler arquivo");
        btnLer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLer, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLer)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        jTabbedPane1.addTab("Ler arquivo", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidoMouseClicked
        // TODO add your handling code here:
        int index = tblPedido.getSelectedRow();
        if(index >= 0 && index<controle.lista.size()){
            Pedido p = controle.lista.get(index);
            txId.setText(Integer.toString(p.getId()));
            txLanche.setText(p.getLanche());
            txAdicional.setText(p.getAdicional());
            txPreco.setText(Float.toString(p.getPreco()));
        }
    }//GEN-LAST:event_tblPedidoMouseClicked

    private void txIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIdActionPerformed

    private void txAdicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txAdicionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txAdicionalActionPerformed

    private void tblPedido1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedido1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPedido1MouseClicked

    private void tblPedido2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedido2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPedido2MouseClicked

    private void bntCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCadastrarActionPerformed
        try {
        int id = Integer.parseInt(txId.getText());
        float preco = Float.parseFloat(txPreco.getText());
        String lanche = txLanche.getText();
        String adicional = txAdicional.getText();
        
        boolean pedidoExiste;
           pedidoExiste = controle.vereficarPedido(id);
           if(pedidoExiste == true){
               JOptionPane.showMessageDialog(null, "Ja existe um pedido registrado com esse id",
                        "Falha ao registrar novo pedido",
                        JOptionPane.ERROR_MESSAGE);
                        txId.setText("");

           }else{
               controle.addPedido(id, lanche, adicional, preco);
               JOptionPane.showMessageDialog(null, "Um novo pedido foi registrado",
                        "Pedido registrado com sucesso",
                        JOptionPane.INFORMATION_MESSAGE);
                        LoadTable();
                        LoadTable1();
                        LoadTable2();
                        txId.setText("");
                        txLanche.setText("");
                        txAdicional.setText("");
                        txPreco.setText("");  
           }
        }catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Todos os campos de cadastro precisam ser preenchidos, id deve ser um numero inteiro e preco deve ser um numero",
                        "Falha ao registrar novo pedido",
                        JOptionPane.ERROR_MESSAGE);
                        txId.setText("");
                        txPreco.setText("");
            System.out.println(nfe);
        }

    }//GEN-LAST:event_bntCadastrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        txId.setText("");
        txLanche.setText("");
        txAdicional.setText("");
        txPreco.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void bntEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditarActionPerformed
        try {
        int id = Integer.parseInt(txId.getText());
        float preco = Float.parseFloat(txPreco.getText());
        String lanche = txLanche.getText();
        String adicional = txAdicional.getText();
        boolean pedidoExiste;
        pedidoExiste = controle.vereficarPedido(id);
           if(pedidoExiste == false){
               JOptionPane.showMessageDialog(null, "Não Existe um Pedido com esse ID, insira um ID cadastrado",
                        "Falha ao editar pedido",
                        JOptionPane.ERROR_MESSAGE);
                        txId.setText("");

           }else{
               controle.editarPedido(id, lanche, adicional, preco);
               JOptionPane.showMessageDialog(null, "o pedido foi editado",
                        "Pedido editado com sucesso",
                        JOptionPane.INFORMATION_MESSAGE);
                        LoadTable();
                        LoadTable1();
                        LoadTable2();
                        txId.setText("");
                        txLanche.setText("");
                        txAdicional.setText("");
                        txPreco.setText("");  
           }
        }catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Todos os campos de cadastro precisam ser preenchidos, id deve ser um numero inteiro e preco deve ser um numero",
                        "Falha ao editar pedido",
                        JOptionPane.ERROR_MESSAGE);
                        txPreco.setText("");
            System.out.println(nfe);
        }

    }//GEN-LAST:event_bntEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
        int id = Integer.parseInt(txId.getText());
        boolean pedidoExiste;
        pedidoExiste = controle.vereficarPedido(id);
           if(pedidoExiste == false){
               JOptionPane.showMessageDialog(null, "Não Existe um Pedido com esse ID, insira um ID cadastrado",
                        "Falha ao excluir pedido",
                        JOptionPane.ERROR_MESSAGE);
                        txId.setText("");

           }else{
               controle.excluirPedido(id);
               JOptionPane.showMessageDialog(null, "o pedido foi excluido",
                        "Pedido excluido com sucesso",
                        JOptionPane.INFORMATION_MESSAGE);
                        LoadTable();
                        LoadTable1();
                        LoadTable2();
                        txId.setText("");
                        txLanche.setText("");
                        txAdicional.setText("");
                        txPreco.setText("");  
           }
        }catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Id deve ser um numero inteiro",
                        "Falha ao excluir pedido",
                        JOptionPane.ERROR_MESSAGE);
                        txId.setText("");
            System.out.println(nfe);
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
        int id = Integer.parseInt(txId.getText());
        boolean pedidoExiste;
        pedidoExiste = controle.vereficarPedido(id);
           if(pedidoExiste == false){
               JOptionPane.showMessageDialog(null, "Não Existe um Pedido com esse ID, insira um ID cadastrado",
                        "Falha ao pesquisar pedido",
                        JOptionPane.ERROR_MESSAGE);
                        txId.setText("");

           }else{
                Pedido pedidopesquisado = controle.pesquisapedido(id);
                txId.setText(Integer.toString(pedidopesquisado.getId()));
                txLanche.setText(pedidopesquisado.getLanche());
                txAdicional.setText(pedidopesquisado.getAdicional());
                txPreco.setText(Float.toString(pedidopesquisado.getPreco()));  
           }
        }catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Id deve ser um numero inteiro",
                        "Falha ao pesquisar pedido",
                        JOptionPane.ERROR_MESSAGE);
                        txId.setText("");
            System.out.println(nfe);
        } 
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        controle.gravar();
        LoadTable();
        LoadTable1();
        LoadTable2();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLerActionPerformed
       try{ 
        controle.lerArquivo();            
        LoadTable();
        LoadTable1();
        LoadTable2();
       }catch(ClassCastException erro){
            JOptionPane.showMessageDialog(null, "Classe Pedido não encontrada",
            "Falha ao Ler arquivo",
            JOptionPane.ERROR_MESSAGE);
       }catch(IOException erro){
           JOptionPane.showMessageDialog(null, "Erro ao ler arquivo binário",
            "Falha ao Ler arquivo",
            JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btnLerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCadastrar;
    private javax.swing.JButton bntEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLer;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTable tblPedido;
    private javax.swing.JTable tblPedido1;
    private javax.swing.JTable tblPedido2;
    private javax.swing.JTextField txAdicional;
    private javax.swing.JTextField txId;
    private javax.swing.JTextField txLanche;
    private javax.swing.JTextField txPreco;
    // End of variables declaration//GEN-END:variables
}
