/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.ControllerLanchonete;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Lanchonete;

/**
 *
 * @author Luan Riechi
 */
public class JanelaLanchonete extends javax.swing.JFrame {
    ControllerLanchonete controle = new ControllerLanchonete();
    
    public void LoadTable (){
        DefaultTableModel modelo = new DefaultTableModel (new Object[]{"Cnpj","Nome","Numerofunc"},0);
        
        for (int i=0 ; i<controle.lista.size();i++){
            Object linha[] = new Object []{controle.lista.get(i).getCnpj(),controle.lista.get(i).getNome(),controle.lista.get(i).getNumerofunc()};
            modelo.addRow(linha);
        
        }
      
        tblLanchonete.setModel(modelo);
    
    }
    public void LoadTable1 (){
        DefaultTableModel modelo = new DefaultTableModel (new Object[]{"Cnpj","Nome","Numerofunc"},0);
        
        for (int i=0 ; i<controle.lista.size();i++){
            Object linha[] = new Object []{controle.lista.get(i).getCnpj(),controle.lista.get(i).getNome(),controle.lista.get(i).getNumerofunc()};
            modelo.addRow(linha);
        
        }
      
        tblLanchonete1.setModel(modelo);
    
    }
    public void LoadTable2 (){
        DefaultTableModel modelo = new DefaultTableModel (new Object[]{"Cnpj","Nome","Numerofunc"},0);
        
        for (int i=0 ; i<controle.lista.size();i++){
            Object linha[] = new Object []{controle.lista.get(i).getCnpj(),controle.lista.get(i).getNome(),controle.lista.get(i).getNumerofunc()};
            modelo.addRow(linha);
        
        }
      
        tblLanchonete2.setModel(modelo);
    
    }    

    /**
     * Creates new form JanelaLanchonete
     */
    public JanelaLanchonete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLanchonete = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txCnpj = new javax.swing.JTextField();
        txNome = new javax.swing.JTextField();
        txNumerofunc = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLanchonete1 = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        bntSalvar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLanchonete2 = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        btnLer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblLanchonete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cnpj", "Nome", "Numero de Funcionarios"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblLanchonete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLanchoneteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLanchonete);

        jLabel1.setText("Cnpj");

        jLabel2.setText("Nome");

        jLabel3.setText("Numero de Funcionarios");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar(Cnpj)");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txCnpj)
                    .addComponent(txNome)
                    .addComponent(txNumerofunc, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnCadastrar)
                .addGap(18, 18, 18)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluir)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisar)
                .addGap(18, 18, 18)
                .addComponent(btnLimpar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txNumerofunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnPesquisar)
                    .addComponent(btnLimpar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Lanchonetes", jPanel1);

        tblLanchonete1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cnpj", "Nome", "Numero de Funcionarios"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblLanchonete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLanchonete1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblLanchonete1);

        bntSalvar.setText("Salvar arquivo");
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntSalvar))
                .addGap(65, 65, 65))
        );

        jTabbedPane1.addTab("Salvar arquivo", jPanel2);

        tblLanchonete2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cnpj", "Nome", "Numero de Funcionarios"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblLanchonete2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLanchonete2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblLanchonete2);

        btnLer.setText("Ler arquivo");
        btnLer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLer, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLer)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        jTabbedPane1.addTab("Ler arquivo", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblLanchoneteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLanchoneteMouseClicked
        // TODO add your handling code here:
        int index = tblLanchonete.getSelectedRow();
        if(index >= 0 && index<controle.lista.size()){
            Lanchonete l = controle.lista.get(index);
            txCnpj.setText(l.getCnpj());
            txNome.setText(l.getNome());
            txNumerofunc.setText(Integer.toString(l.getNumerofunc()));
        }
    }//GEN-LAST:event_tblLanchoneteMouseClicked

    private void tblLanchonete1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLanchonete1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLanchonete1MouseClicked

    private void tblLanchonete2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLanchonete2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLanchonete2MouseClicked

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
        int numero = Integer.parseInt(txNumerofunc.getText());
        String cnpj = txCnpj.getText();
        String nome = txNome.getText();
        boolean lanchoneteExiste;
           lanchoneteExiste = controle.vereficarLanchonete(cnpj);
           if(lanchoneteExiste == true){
               JOptionPane.showMessageDialog(null, "Ja existe uma Lanchonete registrada com esse cnpj",
                        "Falha ao registrar nova Lanchonete",
                        JOptionPane.ERROR_MESSAGE);
                        txCnpj.setText("");

           }else{
               controle.addLanchonete(cnpj, nome, numero);
               JOptionPane.showMessageDialog(null, "Uma nova Lanchonete foi registrado",
                        "Lanchonete registrado com sucesso",
                        JOptionPane.INFORMATION_MESSAGE);
                        LoadTable();
                        LoadTable1();
                        LoadTable2();
                        txCnpj.setText("");
                        txNome.setText("");
                        txNumerofunc.setText("");
           }
        }catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Todos os campos de cadastro precisam ser preenchidos e numero de funcionarios deve ser um numero inteiro",
                        "Falha ao registrar nova Lanchonete",
                        JOptionPane.ERROR_MESSAGE);
                        txNumerofunc.setText("");
            System.out.println(nfe);
        }

    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
        int numero = Integer.parseInt(txNumerofunc.getText());
        String cnpj = txCnpj.getText();
        String nome = txNome.getText();
        boolean lanchoneteExiste;
           lanchoneteExiste = controle.vereficarLanchonete(cnpj);
           if(lanchoneteExiste == false){
               JOptionPane.showMessageDialog(null, "não existe uma Lanchonete registrada com esse cnpj, insira um cnpj cadastrado no sistema",
                        "Falha ao Editar Lanchonete",
                        JOptionPane.ERROR_MESSAGE);
                        txCnpj.setText("");

           }else{
               controle.editarLanchonete(cnpj, nome, numero);
               JOptionPane.showMessageDialog(null, "Uma Lanchonete foi alterada",
                        "Lanchonete Alterada com sucesso",
                        JOptionPane.INFORMATION_MESSAGE);
                        LoadTable();
                        LoadTable1();
                        LoadTable2();
                        txCnpj.setText("");
                        txNome.setText("");
                        txNumerofunc.setText("");
           }
        }catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Todos os campos de cadastro precisam ser preenchidos e numero de funcionarios deve ser um numero inteiro",
                        "Falha ao alterar Lanchonete",
                        JOptionPane.ERROR_MESSAGE);
                        txNumerofunc.setText("");
            System.out.println(nfe);
        }
      
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
        String cnpj = txCnpj.getText();
        boolean lanchoneteExiste;
        lanchoneteExiste = controle.vereficarLanchonete(cnpj);
           if(lanchoneteExiste == false){
               JOptionPane.showMessageDialog(null, "não existe uma Lanchonete registrada com esse cnpj, insira um cnpj cadastrado no sistema",
                        "Falha ao Excluir Lanchonete",
                        JOptionPane.ERROR_MESSAGE);
                        txCnpj.setText("");

           }else{
               controle.excluirLanchonete(cnpj);
               JOptionPane.showMessageDialog(null, "Uma Lanchonete foi Excluida",
                        "Lanchonete Excluida com sucesso",
                        JOptionPane.INFORMATION_MESSAGE);
                        LoadTable();
                        LoadTable1();
                        LoadTable2();
                        txCnpj.setText("");
                        txNome.setText("");
                        txNumerofunc.setText("");
           }
        }catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Deve se utilizar um cnpj cadastrado para excluir uma lanchonete existente",
                        "Falha ao excluir lanchonete",
                        JOptionPane.ERROR_MESSAGE);

            System.out.println(nfe);
        }
       
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
       try{
        String cnpj = txCnpj.getText();
        boolean lanchoneteExiste;
        lanchoneteExiste = controle.vereficarLanchonete(cnpj);
         if(lanchoneteExiste == false){
               JOptionPane.showMessageDialog(null, "não existe uma Lanchonete registrada com esse cnpj, insira um cnpj cadastrado no sistema",
                        "Falha ao Pesquisar Lanchonete",
                        JOptionPane.ERROR_MESSAGE);
                        txCnpj.setText("");

           }else{
            Lanchonete lanchonetepesquisada = controle.pesquisaLanchonete(cnpj);
            txCnpj.setText(lanchonetepesquisada.getCnpj());
            txNome.setText(lanchonetepesquisada.getNome());
            txNumerofunc.setText(Integer.toString(lanchonetepesquisada.getNumerofunc()));
           }
       }catch(NumberFormatException nfe){
           JOptionPane.showMessageDialog(null, "Deve se utilizar um cnpj cadastrado para pesquisar uma lanchonete existente",
                        "Falha ao pesquisar lanchonete",
                        JOptionPane.ERROR_MESSAGE);
           System.out.println(nfe);
       }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        txCnpj.setText("");
        txNome.setText("");
        txNumerofunc.setText(""); 
    }//GEN-LAST:event_btnLimparActionPerformed

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
        controle.gravar();
        LoadTable();
        LoadTable1();
        LoadTable2();
    }//GEN-LAST:event_bntSalvarActionPerformed

    private void btnLerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLerActionPerformed
       try{ 
        controle.lerArquivo();            
        LoadTable();
        LoadTable1();
        LoadTable2();
       }catch(ClassCastException erro){
            JOptionPane.showMessageDialog(null, "Classe Lanchonete não encontrada",
            "Falha ao Ler arquivo",
            JOptionPane.ERROR_MESSAGE);
       }catch(IOException erro){
           JOptionPane.showMessageDialog(null, "Erro ao ler arquivo binário",
            "Falha ao Ler arquivo",
            JOptionPane.ERROR_MESSAGE);
       
       }
    }//GEN-LAST:event_btnLerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaLanchonete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaLanchonete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaLanchonete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaLanchonete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaLanchonete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSalvar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLer;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tblLanchonete;
    private javax.swing.JTable tblLanchonete1;
    private javax.swing.JTable tblLanchonete2;
    private javax.swing.JTextField txCnpj;
    private javax.swing.JTextField txNome;
    private javax.swing.JTextField txNumerofunc;
    // End of variables declaration//GEN-END:variables
}
