/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCliente;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;

/**
 *
 * @author Luan Riechi
 */
public class JanelaCliente extends javax.swing.JFrame {
    ControllerCliente controle = new ControllerCliente();
    
    public void LoadTable (){
        DefaultTableModel modelo = new DefaultTableModel (new Object[]{"ID","Nome","Cpf","Email"},0);
        
        for (int i=0 ; i<controle.lista.size();i++){
            Object linha[] = new Object []{controle.lista.get(i).getIdcliente(),controle.lista.get(i).getNome(),controle.lista.get(i).getCpf(),controle.lista.get(i).getEmail()};
            modelo.addRow(linha);
        
        }
        
        tblCliente.setModel(modelo);
    
    }
    public void LoadTable1 (){
        DefaultTableModel modelo = new DefaultTableModel (new Object[]{"ID","Nome","Cpf","Email"},0);
        
        for (int i=0 ; i<controle.lista.size();i++){
            Object linha[] = new Object []{controle.lista.get(i).getIdcliente(),controle.lista.get(i).getNome(),controle.lista.get(i).getCpf(),controle.lista.get(i).getEmail()};
            modelo.addRow(linha);
        
        }
        
        tblCliente1.setModel(modelo);
    
    }
    public void LoadTable2 (){
        DefaultTableModel modelo = new DefaultTableModel (new Object[]{"ID","Nome","Cpf","Email"},0);
        
        for (int i=0 ; i<controle.lista.size();i++){
            Object linha[] = new Object []{controle.lista.get(i).getIdcliente(),controle.lista.get(i).getNome(),controle.lista.get(i).getCpf(),controle.lista.get(i).getEmail()};
            modelo.addRow(linha);
        
        }
        
        tblCliente2.setModel(modelo);
    
    }     
    
    /**
     * Creates new form JanelaCliente
     */
    public JanelaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txID = new javax.swing.JTextField();
        txNome = new javax.swing.JTextField();
        txCpf = new javax.swing.JTextField();
        txEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        btnRegistrar = new javax.swing.JButton();
        bntEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        bntLimpar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCliente1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        bntSalvar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCliente2 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        btnLerCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("Nome");

        jLabel3.setText("CPF");

        jLabel4.setText("Email");

        txID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIDActionPerformed(evt);
            }
        });

        txNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNomeActionPerformed(evt);
            }
        });

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Cpf", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCliente);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        bntEditar.setText("Editar");
        bntEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar(cpf)");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        bntLimpar.setText("Limpar");
        bntLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(txID, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txNome)
                                    .addComponent(txCpf)
                                    .addComponent(txEmail)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntLimpar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(bntEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnPesquisar)
                    .addComponent(bntLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cliente", jPanel2);

        tblCliente1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Cpf", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCliente1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        bntSalvar.setText("Salvar Arquivo");
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntSalvar))
                .addGap(49, 49, 49))
        );

        jTabbedPane1.addTab("Salvar arquivo", jPanel3);

        tblCliente2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Cpf", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblCliente2);

        btnLerCliente.setText("Ler Arquivo");
        btnLerCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLerClienteMouseClicked(evt);
            }
        });
        btnLerCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLerClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLerCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLerCliente))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ler arquivo", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIDActionPerformed

    private void txNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNomeActionPerformed

    private void bntEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditarActionPerformed
        try {
           String cpf = txCpf.getText();    
           int id = Integer.parseInt(txID.getText());
           String nome = txNome.getText();
           String email= txEmail.getText();
           boolean clienteExiste;
           clienteExiste = controle.vereficarCliente(cpf);
           if(clienteExiste == false){
               JOptionPane.showMessageDialog(null, "Não Existe um Cliente com esse Cpf, insira um cpf cadastrado",
                        "Falha ao Editar cliente",
                        JOptionPane.ERROR_MESSAGE);
                        txCpf.setText("");

           }else{
                controle.editarCliente(cpf, id,nome,email);
                JOptionPane.showMessageDialog(null, "O cliente foi alterado no sistema",
                        "Cliente alterado com sucesso",
                        JOptionPane.INFORMATION_MESSAGE);
                LoadTable();
                LoadTable1();
                LoadTable2();
                txID.setText("");
                txNome.setText("");
                txCpf.setText("");
                txEmail.setText(""); 

           }
        }catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Todos os campos de cadastro precisam ser preenchidos e id deve ser um numero inteiro",
                "Falha ao alterar cliente",
                JOptionPane.ERROR_MESSAGE);            
            System.out.println(nfe);
        } 
       
    }//GEN-LAST:event_bntEditarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
        controle.gravar();
        LoadTable();
        LoadTable1();
        LoadTable2();
    }//GEN-LAST:event_bntSalvarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
        String cpf = txCpf.getText();    
        int id = Integer.parseInt(txID.getText());
        String nome = txNome.getText();
        String email= txEmail.getText();
        boolean clienteExiste;
           clienteExiste = controle.vereficarCliente(cpf);
           if(clienteExiste == true){
               JOptionPane.showMessageDialog(null, "Ja existe um Cliente registrado com esse cpf",
                        "Falha ao registrar novo cliente",
                        JOptionPane.ERROR_MESSAGE);
                        txCpf.setText("");

           }else{
               controle.addCliente(id, nome,cpf , email);
               JOptionPane.showMessageDialog(null, "Um novo cliente foi registrado",
                        "Cliente registrado com sucesso",
                        JOptionPane.INFORMATION_MESSAGE);
                        LoadTable();
                        LoadTable1();
                        LoadTable2();
                        txID.setText("");
                        txNome.setText("");
                        txCpf.setText("");
                        txEmail.setText("");  
           }
        }catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Todos os campos de cadastro precisam ser preenchidos e id deve ser um numero inteiro",
                        "Falha ao registrar novo cliente",
                        JOptionPane.ERROR_MESSAGE);
                        txID.setText("");
            System.out.println(nfe);
        }
      
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try { 
           String cpf = txCpf.getText();
           boolean clienteExiste;
           clienteExiste = controle.vereficarCliente(cpf);
           if(clienteExiste == false){
               JOptionPane.showMessageDialog(null, "Não Existe um Cliente com esse Cpf, insira um cpf cadastrado",
                        "Falha ao Excluir cliente",
                        JOptionPane.ERROR_MESSAGE);
                        txCpf.setText("");

           }else{
                controle.excluirCliente(cpf);
                JOptionPane.showMessageDialog(null, "O cliente foi excluido do sistema",
                        "Cliente excluido com sucesso",
                        JOptionPane.INFORMATION_MESSAGE);
                LoadTable();
                LoadTable1();
                LoadTable2();
                txID.setText("");
                txNome.setText("");
                txCpf.setText("");
                txEmail.setText(""); 

           }
        }catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "Deve se utilizar um cpf cadastrado para excluir um cliente existente",
                        "Falha ao excluir cliente",
                        JOptionPane.ERROR_MESSAGE);
            System.out.println(nfe);
        }        
               
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try { 
           String cpf = txCpf.getText();
           boolean clienteExiste;
           clienteExiste = controle.vereficarCliente(cpf);
           if(clienteExiste == false){
               JOptionPane.showMessageDialog(null, "Não Existe um Cliente com esse Cpf, insira um cpf cadastrado",
                        "Falha ao pesquisar cliente",
                        JOptionPane.ERROR_MESSAGE);
                        txCpf.setText("");

           }else{
                Cliente clientePesquisado = controle.pesquisaCliente(cpf);
                txID.setText(Integer.toString(clientePesquisado.getIdcliente()));
                txNome.setText(clientePesquisado.getNome());
                txCpf.setText(clientePesquisado.getCpf());
                txEmail.setText(clientePesquisado.getEmail());  
           }
        }catch (NumberFormatException nfe){
                JOptionPane.showMessageDialog(null, "Deve se utilizar um cpf cadastrado para pesquisar um cliente existente",
                        "Falha ao pesquisar cliente",
                        JOptionPane.ERROR_MESSAGE);
            System.out.println(nfe);
        }
       
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void bntLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLimparActionPerformed
        // TODO add your handling code here:
        txID.setText("");
        txNome.setText("");
        txCpf.setText("");
        txEmail.setText("");        
    }//GEN-LAST:event_bntLimparActionPerformed

    private void btnLerClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLerClienteMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnLerClienteMouseClicked

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
        // TODO add your handling code here:
        int index = tblCliente.getSelectedRow();
        if(index >= 0 && index<controle.lista.size()){
            Cliente c = controle.lista.get(index);
            txID.setText(Integer.toString(c.getIdcliente()));
            txNome.setText(c.getNome());
            txCpf.setText(c.getCpf());
            txEmail.setText(c.getEmail());  
        }        
    }//GEN-LAST:event_tblClienteMouseClicked

    private void btnLerClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLerClienteActionPerformed
       try{ 
        controle.lerArquivo();            
        LoadTable();
        LoadTable1();
        LoadTable2();
       }catch(ClassCastException erro){
            JOptionPane.showMessageDialog(null, "Classe Cliente não encontrada",
            "Falha ao Ler arquivo",
            JOptionPane.ERROR_MESSAGE);
       }catch(IOException erro){
           JOptionPane.showMessageDialog(null, "Erro ao ler arquivo binário",
            "Falha ao Ler arquivo",
            JOptionPane.ERROR_MESSAGE);
       
       }
    }//GEN-LAST:event_btnLerClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEditar;
    private javax.swing.JButton bntLimpar;
    private javax.swing.JButton bntSalvar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLerCliente;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTable tblCliente1;
    private javax.swing.JTable tblCliente2;
    private javax.swing.JTextField txCpf;
    private javax.swing.JTextField txEmail;
    private javax.swing.JTextField txID;
    private javax.swing.JTextField txNome;
    // End of variables declaration//GEN-END:variables
}
